dist: trusty
sudo: required
language: node_js
node_js:
  - "9.4.0"

matrix:
  include:
    - os: linux
      dist: trusty
      before_install: 
      - npm i -g ganache-cli@6.1.0
      - ganache-cli &>/dev/null &
        

install:
  - npm install

script:
  - npm run migrate
  - npm run test
